# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='end_reason',
            field=models.CharField(
                choices=[
                    ('checkmate', 'Checkmate'),
                    ('stalemate', 'Stalemate'),
                    ('resign', 'Resignation'),
                    ('timeout', 'Timeout'),
                    ('agreement', 'Agreement'),
                    ('threefold_repetition', 'Threefold Repetition'),
                    ('fifty_move_rule', 'Fifty-Move Rule'),
                    ('insufficient_material', 'Insufficient Material'),
                ],
                max_length=25,
            ),
        ),
    ]
